/**
 * "Blank canvas" preset — the exact scene snapshot applied when the homepage
 * "Blank canvas" link is used. A truly minimal void: HDRI lighting on but its
 * panorama hidden (solid black background), lights off, ground wireframe on.
 *
 * Shape matches a Copy Settings / `.orby` export so it round-trips cleanly
 * through {@link SceneSettingsManager#loadFromText}. Returns a fresh object on
 * every call so callers can mutate/serialize without touching the source.
 *
 * @returns {object}
 */
export function createBlankCanvasPreset() {
  return {
    shading: 'shaded',
    scale: 1,
    xOffset: 0,
    yOffset: 0,
    zOffset: 0,
    rotationX: 0,
    rotationY: 0,
    rotationZ: 0,
    autoRotate: 0,
    autoRotateDirection: 'forward',
    moveWidgetEnabled: false,
    rotateWidgetEnabled: false,
    scaleWidgetEnabled: false,
    material: {
      brightness: 1.75,
      metalness: 0,
      roughness: 0.5,
      emissive: 0,
      importHasMrMaps: false,
      importUsesAuthoredPbr: false,
    },
    advanced: {
      reverseNormals: false,
      transparencyFix: 'default',
      glassOpacity: 0.45,
      glassReflection: 2,
      glassTint: '#080808',
      glassBody: 0,
      blendSortingMitigation: true,
      flipGlassNormalMapY: false,
      glassFrontFacesOnly: false,
      uvChecker: false,
      uvCheckerScale: 5,
      uvCheckerStyle: 'orby',
      normalView: false,
      normalViewMode: 'geometry',
      stlSmoothShading: false,
      stlSmoothingAngle: 40,
    },
    clay: {
      color: '#808080',
      normalMap: true,
    },
    wireframe: {
      alwaysOn: false,
      color: '#c4ff00',
      onlyVisibleFaces: true,
      hideMesh: false,
      thickness: 1,
      opacity: 1,
    },
    creativeLook: {
      enabled: false,
      preset: null,
      pauseShaderAnimations: false,
      shaderAnimationSpeed: 0.4,
      patternScale: 1,
      masterHue: 0,
      intensity: 1,
      liftCrush: 0,
      viewportBloom: false,
      presetParams: {},
    },
    fresnel: {
      enabled: false,
      color: '#808080',
      radius: 2,
      strength: 0.3,
    },
    subsurface: {
      enabled: false,
      translucency: 0,
      scatterTint: '#ffd4b8',
    },
    fbxMapSlots: {
      enabled: false,
      activeMaterial: '',
      defaults: {
        normalConvention: 'match-albedo',
        pbrUvChannel: 0,
        ormPacking: 'gltf',
      },
      materials: {},
    },
    fontExtrude: {
      panelOpen: false,
      align: 'center',
      tracking: 0,
      kerning: 'metrics',
      lineHeight: 1,
      detail: 'high',
      bevelType: 'straight',
      previewScale: 0.65,
      fillColor: '#808080',
      revealDurationSec: 2,
      revealType: 'scale',
      revealUnit: 'character',
      revealLoop: true,
      pauseAllAnimations: false,
      revealSlideDepth: 0.18,
      revealSlideTime: 1.3,
      revealSlideDirection: 'back',
      revealEmissiveSlam: false,
      revealEmissiveStrength: 1,
      revealEmissiveDecaySec: 0.35,
      revealEmissiveColor: '#c4ff00',
      constantType: 'none',
      constantIntensity: 0.5,
      constantSpeedSec: 2,
      constantSpread: 1,
      sourceText: '',
      circularWrapEnabled: false,
      circularWrapMode: 'auto',
      circularWrapArcDeg: 360,
      postscriptName: '',
      customFontAsset: null,
    },
    svgExtrude: {
      enabled: false,
      availableColors: [],
      depth: 0.2,
      normalAngle: 30,
      hardEdgeAngle: 45,
      colorDepths: {},
      colorOffsets: {},
      colorReplacements: {},
      flipDirection: false,
      colorOverride: false,
      overrideColor: '#7ed321',
      surfacePreset: 'none',
      surfaceScale: 1,
      surfaceStrength: 1,
      bevelAmount: 0,
      detail: 'high',
    },
    hdri: 'beach',
    hdriCustomName: null,
    hdriCustomAsset: null,
    hdriEnabled: true,
    hdriStrength: 2,
    hdriBlurriness: 0,
    hdriRotation: 0,
    hdriBackground: false,
    hdriReceiveShadowsAo: false,
    groundSolid: false,
    groundWire: true,
    groundWireOpacity: 1,
    groundY: 0,
    gridY: 0,
    baseScale: 1,
    gridScale: 1,
    gridLineWidth: 1,
    baseMetalness: 0.08,
    baseRoughness: 0.5,
    baseReflection: 1,
    baseClearcoat: 0,
    baseSurfacePreset: 'none',
    baseSurfaceScale: 1,
    baseSurfaceStrength: 1,
    baseGlassSurface: false,
    baseGlassBlur: 0.1,
    baseGlassAmount: 0.5,
    baseGlassBrightness: 0.1,
    backdropEnabled: false,
    backdropScale: 1,
    backdropWidth: 2,
    backdropColor: '#808080',
    backdropRotation: 0,
    backdropY: 0,
    backdropMetalness: 0.02,
    backdropRoughness: 0.9,
    backdropSurfacePreset: 'none',
    backdropSurfaceScale: 1,
    backdropSurfaceStrength: 1,
    groundSolidColor: '#808080',
    groundWireColor: '#c4ff00',
    lensFlare: {
      enabled: false,
      rotation: 0,
      height: 15,
      color: '#d28756',
      quality: 'high',
      haloIntensity: 1,
      streakLength: 5,
      sunDiscScale: 1.5,
      sunDiscBlur: 1.25,
      sunDiscColor: '#fff0c8',
      discGlowIntensity: 0,
      discGlowSize: 5,
      discGlowColor: '#ff8844',
      spinDuringOrbit: false,
      keyLightConnected: false,
      keyLightRestore: null,
      anamorphicBloom: {
        enabled: false,
        quality: 'medium',
        strength: 1,
        spread: 0.2,
        streakAngle: 0,
        threshold: 0.7,
        soften: 0.12,
        streakTint: '#7ec8ff',
      },
    },
    godRays: {
      enabled: false,
      color: '#ffe8c4',
      lightScale: 0.4,
      opacity: 1,
      density: 0.96,
      decay: 0.92,
      weight: 0.4,
      exposure: 0.6,
      clampMax: 1,
      blur: true,
      quality: 'medium',
    },
    lights: {
      key: {
        color: '#ffdfc9',
        intensity: 1.28,
        height: 5,
        rotate: 0,
        enabled: false,
        castShadows: false,
      },
      fill: {
        color: '#b0c7ff',
        intensity: 0.8,
        height: 3,
        rotate: 0,
        enabled: false,
        castShadows: false,
      },
      rim: {
        color: '#a0eaf9',
        intensity: 0.96,
        height: 4,
        rotate: 0,
        enabled: false,
        castShadows: false,
      },
      ambient: {
        color: '#7c8ca6',
        intensity: 0.48,
        enabled: false,
      },
    },
    lightsEnabled: false,
    lightsMaster: 0.3,
    lightsRotation: 0,
    lightsHeight: 5,
    lightsAutoRotate: false,
    showLightIndicators: false,
    lightsCastShadows: false,
    lightsShadowQuality: 'medium',
    lightsShadowSoftness: 0.6,
    lightsShadowColor: '#080808',
    lightsShadowOpacity: 0.25,
    lightsShadowContactOffset: -0.0005,
    lightsShadowNormalBias: 0.01,
    lightsShadowTwoSided: false,
    gobo: {
      enabled: false,
      panelOpen: false,
      texture: 'palm',
      softness: 0.3,
      scale: 5,
      scaleSpace: 'ui',
      rotation: 0,
    },
    dof: {
      enabled: false,
      focus: 1.5,
      focusMode: 'auto',
      aperture: 0.003,
      foregroundBlur: 1,
      backgroundBlur: 1,
      zoomAttenuation: true,
      quality: 'high',
      showFocusPlane: false,
    },
    bloom: {
      enabled: true,
      threshold: 1,
      strength: 0.2,
      radius: 0.2,
      color: '#ffb3d9',
      quality: 'medium',
    },
    lensDirt: {
      enabled: false,
      strength: 0.8,
      minLuminance: 0.55,
      maxLuminance: 0.95,
      sensitivity: 0.55,
      tintColor: '#ffffff',
    },
    grain: {
      enabled: false,
      intensity: 0.03,
      scale: 1,
      color: '#ffffff',
    },
    aberration: {
      enabled: false,
      amount: 0.0006,
    },
    ambientOcclusion: {
      enabled: false,
      intensity: 3,
      radius: 1,
      quality: 'medium',
      color: '#080808',
    },
    fisheye: {
      enabled: false,
      horizontalFOVDeg: 131,
      strength: 0.37,
      cylindricalRatio: 4,
    },
    exposure: 1,
    autoExposure: false,
    histogramEnabled: false,
    toneCurveOpen: false,
    toneCurve: {
      blackY: 0,
      whiteY: 1,
      p1: { x: 1 / 3, y: 1 / 3 },
      p2: { x: 2 / 3, y: 2 / 3 },
    },
    antiAliasing: 'fxaa',
    renderQuality: 'medium',
    toneMapping: 'aces-filmic',
    background: '#000000',
    backgroundSolidEnabled: true,
    backgroundGradient: {
      enabled: false,
      type: 'linear',
      angle: 180,
      centerX: 50,
      centerY: 50,
      stops: [
        { color: '#000000', position: 0 },
        { color: '#c4ff00', position: 100 },
      ],
    },
    backgroundImage: {
      enabled: false,
      fit: 'cover',
      asset: null,
    },
    lookFilterPreset: 'none',
    lookFilterPresetsOpen: false,
    creativeLookSectionOpen: false,
    svgColorDetail: 'high',
    camera: {
      fov: 45,
      lensFocalMm: null,
      lensSensorId: 'aps-c',
      tilt: 0,
      worldPosition: { x: 0, y: 1.2, z: 2.4 },
      distance: 2.4083189157584592,
      viewPreset: 'front',
      compositionGridEnabled: false,
      compositionGuidesInverted: false,
      compositionPortraitCropGuide: false,
      cinematicLetterbox219: false,
      autoOrbit: 'off',
      handheld: 'off',
      contrast: 1,
      temperature: 6000,
      tint: 0,
      highlights: 0,
      shadows: 0,
      saturation: 1,
      clarity: 0,
      fade: 0,
      sharpness: 0,
      vignetteEnabled: false,
      vignette: 0.5,
      vignetteColor: '#080808',
      isometric: {
        enabled: false,
        presetId: 'true-isometric',
        horizontalDeg: 45,
        verticalDeg: 35.264389682754654,
        panUnlocked: false,
      },
      clipPlanes: {
        manual: false,
        near: 0.1,
        far: 100,
      },
      position: { x: 0, y: 1.2, z: 2.4 },
      target: { x: 0, y: 1, z: 0 },
    },
    animation: {
      showBones: false,
      showJointNames: false,
      hideMesh: false,
      jointScale: 0.5,
      boneStrokeWidth: 2,
      clipPlaybackMode: 'loop',
      displayFps: 60,
      timeReferenceEnabled: false,
    },
    colorChecker: {
      enabled: false,
      distance: 2,
      rotate: 333,
      height: -0.5,
      scale: 0.0552366175329713,
      rawColors: false,
    },
    baseColor: '#d4c5a9',
    exportSettings: {
      format: 'png',
      transparent: true,
      size: 2,
      sections: {
        image: false,
        svg: false,
        glb: false,
        video: false,
      },
      video: {
        turntable: true,
        orbit: false,
        zoomIn: false,
        zoomOut: false,
        tiltLeft: false,
        tiltRight: false,
        zoomDistance: 1.5,
        tiltAngle: 15,
        fovOffset: 0,
        pitchOffset: 0,
        format: 'mp4',
        durationSec: 5,
        spins: 1,
        subtleSpinDegrees: 0,
        spinDirection: 'forward',
        hdriRotationDegrees: 0,
        fps: 24,
        resolution: '1080p',
        aspectRatio: '16:9',
        mp4Quality: 'medium',
        movTransparent: false,
        meshAnimationsInclude: false,
        meshAnimationClipIndex: 0,
      },
    },
  };
}
