/**
 * Build a self-hosted Font Awesome solid subset from icons used in the repo.
 * Scans HTML/JS/CSS, extracts matching rules from @fortawesome/fontawesome-free,
 * and subsets fa-solid-900.woff2.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'fs';
import { dirname, join, relative, resolve } from 'path';
import { fileURLToPath } from 'url';
import subsetFont from 'subset-font';
import * as esbuild from 'esbuild';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');
const faRoot = join(repoRoot, 'node_modules/@fortawesome/fontawesome-free');
const cssOut = join(repoRoot, 'styles/fontawesome/orby-icons.css');
const fontOut = join(repoRoot, 'assets/vendor/fontawesome/webfonts/fa-solid-900.woff2');
const manifestOut = join(repoRoot, 'styles/fontawesome/icons.json');

/** Not icon glyphs — FA style/utility class suffixes. */
const IGNORE_ICON_NAMES = new Set([
  'solid',
  'regular',
  'brands',
  'classic',
  'sharp',
  'sr-only',
  'sr-only-focusable',
  'fw',
  'ul',
  'li',
  'border',
  'pull-left',
  'pull-right',
  'beat',
  'bounce',
  'fade',
  'beat-fade',
  'flip',
  'shake',
  'spin',
  'spin-pulse',
  'spin-reverse',
  'pulse',
  'inverse',
  'stack',
  'stack-1x',
  'stack-2x',
  'rotate-90',
  'rotate-180',
  'rotate-270',
  'flip-horizontal',
  'flip-vertical',
  'flip-both',
  'rotate-by',
  '1x',
  '2x',
  '3x',
  '4x',
  '5x',
  '6x',
  '7x',
  '8x',
  '9x',
  '10x',
  '2xs',
  'xs',
  'sm',
  'lg',
  'xl',
  '2xl',
]);

const SCAN_ROOTS = [
  repoRoot,
  join(repoRoot, 'scripts'),
  join(repoRoot, 'about'),
  join(repoRoot, 'brand'),
  join(repoRoot, 'credits'),
  join(repoRoot, 'legal'),
  join(repoRoot, 'stats'),
  join(repoRoot, 'support'),
];

const SCAN_EXTENSIONS = new Set(['.html', '.js', '.css', '.mjs']);

/** @param {string} dir @param {(file: string) => void} visit */
function walk(dir, visit) {
  for (const name of readdirSync(dir)) {
    if (name === 'node_modules' || name === 'dist' || name === '.git') continue;
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) {
      walk(full, visit);
      continue;
    }
    visit(full);
  }
}

/** @returns {Set<string>} */
function collectUsedIconNames() {
  const names = new Set();

  /** @param {string} text */
  function scanText(text) {
    const patterns = [
      /\bfa-solid\s+fa-([a-z0-9-]+)\b/g,
      /\bfa-regular\s+fa-([a-z0-9-]+)\b/g,
      /\bfa-brands\s+fa-([a-z0-9-]+)\b/g,
      /classList\.(?:toggle|add|remove)\(\s*['"]fa-([a-z0-9-]+)['"]/g,
      /['"]fa-([a-z0-9-]+)['"]/g,
      /\.fa-([a-z0-9-]+)\b/g,
    ];
    for (const re of patterns) {
      for (const match of text.matchAll(re)) {
        const name = match[1];
        if (!IGNORE_ICON_NAMES.has(name)) names.add(name);
      }
    }
  }

  const fontawesomeOutDir = join(repoRoot, 'styles', 'fontawesome');

  for (const root of SCAN_ROOTS) {
    walk(root, (file) => {
      const ext = file.slice(file.lastIndexOf('.'));
      if (!SCAN_EXTENSIONS.has(ext)) return;
      if (file.startsWith(fontawesomeOutDir)) return;
      const text = readFileSync(file, 'utf8');
      scanText(text);
    });
  }

  return names;
}

/** @param {string} css @returns {Map<string, { rule: string, codepoint: number }>} */
function parseIconRules(css) {
  /** @type {Map<string, { rule: string, codepoint: number }>} */
  const byName = new Map();
  const ruleRe = /([^{}]+)\{content:"(\\[^"]+)"\}/g;

  for (const match of css.matchAll(ruleRe)) {
    const selectors = match[1];
    const escaped = match[2];
    const codepoint = parseInt(escaped.slice(1), 16);
    if (!Number.isFinite(codepoint)) continue;

    const rule = `${selectors}{content:"${escaped}"}`;
    for (const sel of selectors.split(',')) {
      const iconMatch = sel.match(/\.fa-([a-z0-9-]+):before\b/);
      if (!iconMatch) continue;
      byName.set(iconMatch[1], { rule, codepoint });
    }
  }

  return byName;
}

const BASE_CSS = `/*!
 * Font Awesome Free 6.5.1 subset — https://fontawesome.com
 * License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
 * Generated by scripts/buildFontAwesomeSubset.mjs — do not edit
 */
:root,:host{--fa-style-family-classic:"Font Awesome 6 Free";--fa-font-solid:normal 900 1em/1 "Font Awesome 6 Free"}
.fa{font-family:var(--fa-style-family,"Font Awesome 6 Free");font-weight:var(--fa-style,900)}
.fa,.fa-solid,.fas{-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased;display:var(--fa-display,inline-block);font-style:normal;font-variant:normal;line-height:1;text-rendering:auto}
.fa-solid,.fas{font-family:"Font Awesome 6 Free";font-weight:900}
@font-face{font-family:"Font Awesome 6 Free";font-style:normal;font-weight:900;font-display:block;src:url("../../assets/vendor/fontawesome/webfonts/fa-solid-900.woff2") format("woff2")}
`;

/**
 * @param {{ minify?: boolean }} [options]
 */
export async function buildFontAwesomeSubset(options = {}) {
  const minify = options.minify !== false;
  const usedNames = collectUsedIconNames();
  const faCss = readFileSync(join(faRoot, 'css/fontawesome.min.css'), 'utf8');
  const iconRules = parseIconRules(faCss);

  const missing = [];
  const rulesByCodepoint = new Map();

  for (const name of [...usedNames].sort()) {
    const entry = iconRules.get(name);
    if (!entry) {
      missing.push(name);
      continue;
    }
    if (!rulesByCodepoint.has(entry.codepoint)) {
      rulesByCodepoint.set(entry.codepoint, entry.rule);
    }
  }

  if (missing.length) {
    throw new Error(`Unknown Font Awesome icons: ${missing.join(', ')}`);
  }

  const codepoints = [...rulesByCodepoint.keys()].sort((a, b) => a - b);
  const iconCss = [...rulesByCodepoint.values()].join('');
  let css = `${BASE_CSS}${iconCss}`;

  if (minify) {
    css = (await esbuild.transform(css, { loader: 'css', minify: true })).code;
  }

  mkdirSync(dirname(cssOut), { recursive: true });
  mkdirSync(dirname(fontOut), { recursive: true });

  const fontBuffer = readFileSync(join(faRoot, 'webfonts/fa-solid-900.woff2'));
  const subsetText = String.fromCodePoint(...codepoints);
  const subsetBuffer = await subsetFont(fontBuffer, subsetText, {
    targetFormat: 'woff2',
  });

  writeFileSync(cssOut, css);
  writeFileSync(fontOut, subsetBuffer);
  writeFileSync(
    manifestOut,
    `${JSON.stringify(
      {
        version: '6.5.1',
        style: 'solid',
        icons: [...usedNames].sort(),
        codepoints: codepoints.map((cp) => `0x${cp.toString(16)}`),
      },
      null,
      2,
    )}\n`,
  );

  return {
    cssOut,
    fontOut,
    iconCount: usedNames.size,
    cssBytes: Buffer.byteLength(css, 'utf8'),
    fontBytes: subsetBuffer.length,
  };
}

const isCli = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isCli) {
  const result = await buildFontAwesomeSubset();
  console.log(
    `Wrote ${relative(repoRoot, result.cssOut)} (${result.cssBytes} bytes, ${result.iconCount} icons)`,
  );
  console.log(
    `Wrote ${relative(repoRoot, result.fontOut)} (${result.fontBytes} bytes)`,
  );
}
